# INSTRUCTIONS:
# This is an AWS CDK app that creates an S3 bucket with versioning and encryption.
# To run:
#   1. Install dependencies: pip install aws-cdk-lib constructs
#   2. Ensure you have AWS CDK CLI installed (npm install -g aws-cdk)
#   3. Save this file as app.py
#   4. Run 'cdk synth' to generate CloudFormation template
#   5. To deploy: 'cdk deploy'
# No additional inputs are required; the bucket name will be auto-generated by CDK.
# To customize the bucket name, set context: cdk synth -c bucket_name=my-bucket
# The bucket uses SSE-S3 encryption and versioning enabled.
# Default removal policy is DESTROY for dev environments; change if needed.
# END INSTRUCTIONS

from aws_cdk import (
    App,
    Stack,
    CfnOutput,
    RemovalPolicy,
    aws_s3 as s3,
)
from constructs import Construct

class S3BucketStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Create S3 bucket with versioning and encryption
        bucket = s3.Bucket(
            self,
            "MyBucket",
            versioned=True,
            encryption=s3.BucketEncryption.S3_MANAGED,  # SSE-S3
            removal_policy=RemovalPolicy.DESTROY,  # For dev; use RETAIN for prod
            auto_delete_objects=True,  # Required for DESTROY removal policy
        )

        # Output bucket name
        CfnOutput(self, "BucketName", value=bucket.bucket_name)

app = App()
S3BucketStack(app, "S3BucketStack")
app.synth()
