#!/usr/bin/env bash
# Provision a Multipass VM as the on-premises target for the live-deployment
# arm of the evaluation campaign, and write the inventory that points at it.
#
#   scripts/setup_multipass_target.sh          # create (or re-use) the VM
#   scripts/setup_multipass_target.sh --recreate
#   scripts/setup_multipass_target.sh --destroy
#
# Multipass VMs are reachable over SSH from the host, but Multipass keeps its
# own key under a root-only path.  Rather than escalating to read it, this
# script generates a dedicated key pair and injects the public half via
# cloud-init at launch, so the campaign runs as an ordinary user.
set -u

VM_NAME="${VM_NAME:-syssecops-eval}"
VM_CPUS="${VM_CPUS:-1}"
VM_MEMORY="${VM_MEMORY:-1G}"
VM_DISK="${VM_DISK:-5G}"
VM_IMAGE="${VM_IMAGE:-22.04}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURE_DIR="${REPO_ROOT}/examples/eval-fixtures/ansible"
INVENTORY="${FIXTURE_DIR}/deploy-inventory.ini"
KEY_DIR="${REPO_ROOT}/.eval-target"
KEY_FILE="${KEY_DIR}/id_ed25519"

die() { echo "error: $*" >&2; exit 1; }

command -v multipass >/dev/null 2>&1 || die "multipass not found on PATH"

if [ "${1:-}" = "--destroy" ]; then
    multipass delete --purge "${VM_NAME}" 2>/dev/null
    rm -f "${INVENTORY}"
    echo "destroyed ${VM_NAME} and removed ${INVENTORY##"${REPO_ROOT}/"}"
    exit 0
fi

if [ "${1:-}" = "--recreate" ]; then
    multipass delete --purge "${VM_NAME}" 2>/dev/null
fi

# --------------------------------------------------------------------------- #
# Key pair
# --------------------------------------------------------------------------- #
mkdir -p "${KEY_DIR}"
chmod 700 "${KEY_DIR}"
if [ ! -f "${KEY_FILE}" ]; then
    ssh-keygen -t ed25519 -N "" -C "syssecops-eval-target" -f "${KEY_FILE}" >/dev/null \
        || die "ssh-keygen failed"
    echo "generated key ${KEY_FILE##"${REPO_ROOT}/"}"
fi

# --------------------------------------------------------------------------- #
# Virtual machine
# --------------------------------------------------------------------------- #
if multipass info "${VM_NAME}" >/dev/null 2>&1; then
    echo "re-using existing VM ${VM_NAME}"
    multipass start "${VM_NAME}" >/dev/null 2>&1
else
    CLOUD_INIT="$(mktemp)"
    trap 'rm -f "${CLOUD_INIT}"' EXIT
    cat > "${CLOUD_INIT}" <<EOF
#cloud-config
ssh_authorized_keys:
  - $(cat "${KEY_FILE}.pub")
package_update: false
packages:
  - iptables
EOF
    echo "launching ${VM_NAME} (${VM_IMAGE}, ${VM_CPUS} cpu, ${VM_MEMORY} ram)..."
    multipass launch "${VM_IMAGE}" \
        --name "${VM_NAME}" \
        --cpus "${VM_CPUS}" \
        --memory "${VM_MEMORY}" \
        --disk "${VM_DISK}" \
        --cloud-init "${CLOUD_INIT}" \
        || die "multipass launch failed"
fi

VM_IP="$(multipass info "${VM_NAME}" --format csv | awk -F, 'NR==2 {print $3}')"
[ -n "${VM_IP}" ] || die "could not determine the address of ${VM_NAME}"

# --------------------------------------------------------------------------- #
# Inventory
# --------------------------------------------------------------------------- #
# The group name must stay [appservers]: the fixture playbooks declare
# `hosts: appservers`, and ansible-playbook exits 0 with an empty PLAY RECAP
# when nothing matches, so a mismatched group would record a deploy that never
# ran as a successful apply.
cat > "${INVENTORY}" <<EOF
; Generated by scripts/setup_multipass_target.sh -- do not edit by hand.
[appservers]
eval-target ansible_host=${VM_IP}

[appservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${KEY_FILE}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null
EOF

echo "wrote ${INVENTORY##"${REPO_ROOT}/"} -> ${VM_IP}"

# --------------------------------------------------------------------------- #
# Prove the target is usable before the campaign depends on it
# --------------------------------------------------------------------------- #
if command -v ansible >/dev/null 2>&1; then
    echo "checking authenticated access..."
    if ansible all -i "${INVENTORY}" -m ping >/dev/null 2>&1 \
       && ansible all -i "${INVENTORY}" -m command -a "id -u" --become >/dev/null 2>&1; then
        echo "ok: reachable, authenticated, and privilege escalation works"
    else
        echo "warning: ansible could not reach or escalate on ${VM_IP}" >&2
        echo "  try: ansible all -i ${INVENTORY} -m ping -vvv" >&2
        exit 1
    fi
else
    echo "note: ansible not on PATH; skipped the reachability check"
fi

cat <<EOF

Run the live-target arm with:
  .venv/bin/python -m evaluation.run_campaign \\
      --scenario ans-pass-deploy --scenario ans-reject-deploy-blocked \\
      --allow target-host --campaign-id rq2_deploy
EOF
